transformerlab/transformerlab-app

package-lock.json, package.json, release/app/package-lock.json, src/main/preload.ts, src/main/ssh-client.js, src/main/util.ts, src/renderer/App.tsx, src/renderer/components/AutoUpdateModal.tsx, src/renderer/components/Computer.tsx, src/renderer/components/Connect/LocalConnection.tsx, src/renderer/components/Connect/context/index.ts, src/renderer/components/Connect/context/localConnectionContext.tsx, src/renderer/components/Connect/types/Message.ts, src/renderer/components/Connect/utils/index.ts, src/renderer/components/Connect/utils/isStep.ts, src/renderer/components/Connect/utils/setIntervalXTimes.ts, src/renderer/components/Logs.tsx, src/renderer/components/MainAppPanel.tsx, src/renderer/components/ModelCurrentlyPlayingBar.tsx, src/renderer/components/TransformerLabSettings.tsx, src/renderer/components/Welcome.tsx, src/renderer/preload.d.ts
- Updates a few JS packages that had security alerts to latest patch version
- Adds `@types/electron` package
- Cleans up some TS issues in `LocalConnection`
=> update deps + fix some TS

src/renderer/components/Data/DataStore.tsx, src/renderer/components/Data/PreviewDatasetModal.tsx, src/renderer/lib/transformerlab-api-sdk.ts
and updating SDK to include new params for preview get request.
=> Updating PreviewDatasetModal to include pagination

src/renderer/components/Data/DatasetInfoModal.tsx
=> Fixing DatasetInfoDialog close button so that it's easier to click

src/renderer/components/Experiment/Train/TrainLoRA.tsx
Fixed the training status text when a failure occurs from success to failure
=> Fixed the training status text when a failure occurs from success to failure

src/renderer/components/Experiment/Train/LoRATrainingRunButton.tsx
=> Block train start if either the dataset or the model is not downloaded, and download the necessary pieces instead

src/renderer/components/Nav/Sidebar.tsx
Updated the plugins disabled option to 'false' as it is independent of any experiment
=> UI fix - Updated plugins option

src/renderer/components/Experiment/Eval/EvalJobsTable.tsx
We add checkboxes to the Eval page. Later on we can use this feature to allow us to select multiple evals and compare them.
=> Add checkboxes to the Evals page -- will be used for compare

src/renderer/components/Experiment/Eval/EvalJobsTable.tsx, src/renderer/components/Experiment/Eval/EvalModal.tsx, src/renderer/components/Settings/TransformerLabSettings.tsx
- Enable Tensorboard option within evals
- Remove the deletion of the template_name in formJson of Evals
=> Add Tensorboard to evals

src/renderer/components/Experiment/Eval/Chart.tsx
- Change approach to prevent overlapping Radarcharts as separate figures
- Add Swap Axes for line charts
- Refactor code to use less compareChart and a single data object across all three figures
=> Fix Compare Evals

src/renderer/components/Experiment/Eval/EvalJobsTable.tsx, src/renderer/components/Experiment/Eval/ViewCSVModal.tsx
- Fixes and shows correct detailed report when opening an individual report after a compare report
=> Detailed Report Bug

src/renderer/components/Experiment/DynamicPluginForm.tsx, src/renderer/components/Experiment/Eval/EvalTasksTable.tsx, src/renderer/components/Experiment/Widgets/CustomGEvalWidget.tsx
- Also fix the tasks list to have commas when custom tasks are involved
=> Add GEval Widget

src/renderer/components/Experiment/Eval/EvalTasksTable.tsx, src/renderer/components/Experiment/Foundation/CurrentFoundationInfo.tsx, src/renderer/components/Experiment/Train/TrainingModalLoRA.tsx
- Also corrects the formatTemplate for evalTasks table
=> Change message for Provenance not found 

src/renderer/components/Plugins/PluginCard.tsx, src/renderer/components/Plugins/PluginGallery.tsx
=> Greying out plugins, still can install of unsupported architectures

src/renderer/components/Experiment/Foundation/CurrentFoundationInfo.tsx
=> Add tabs within Foundation section

src/renderer/components/Connect/LoginModal.tsx, src/renderer/components/Experiment/ExperimentNotes.tsx
=> Have the Cloud App look for the API on the current server

src/renderer/components/Computer.tsx
=> Add MacMon Specific Metrics

src/renderer/components/Experiment/Interact/Interact.tsx, src/renderer/components/MainAppPanel.tsx
=> Add filtering based on the supports field for interact in loader plugins

src/renderer/components/Experiment/Interact/Interact.tsx
Fixes transformerlab/transformerlab-app#36
=> Fix Token Count in Interact tab

src/renderer/components/Experiment/Train/JobProgress.tsx
=> Fix start time to not show future times

src/main/main.ts
- Fixes #57 
- If the app crashes more than 3 times in 2 minutes then it won't restart, otherwise it will show a dialog box and restart on its own for uncaught exceptions only
=> Fix the app restart on crash

src/renderer/components/ModelZoo/LocalModelsTable.tsx, src/renderer/lib/transformerlab-api-sdk.ts
=> Delete models from HF cache

src/renderer/components/Data/LocalDatasets.tsx
=> Show Dataset Name on Data card if available

src/renderer/App.tsx, src/renderer/components/Experiment/Foundation/CurrentFoundationInfo.tsx, src/renderer/components/Experiment/Foundation/ModelDetails.tsx, src/renderer/components/Experiment/Foundation/RunModelButton.tsx, src/renderer/components/Experiment/Foundation/SelectAModel.tsx, src/renderer/components/Experiment/Foundation/index.tsx, src/renderer/components/MainAppPanel.tsx
=> Open console logger upon a failed inference server run

src/renderer/components/Plugins/LocalPlugins.tsx, src/renderer/components/Plugins/PluginCard.tsx
=> Fix supported arch message for local plugins

src/renderer/components/Experiment/Export/Export.tsx, src/renderer/styles.css
Changed runningPlugin from a True/False variable to the actual plugin ID.
=> All exporter plugins showing 'Exporting...' when one runs

src/renderer/components/Experiment/Train/TrainLoRA.tsx
=> Fix info icon for training jobs

src/renderer/components/Data/DatasetCard.tsx, src/renderer/components/Data/LocalDatasets.tsx
=> Fix internal error on Datasets tab due to name field

src/renderer/components/Plugins/PluginCard.tsx, src/renderer/components/Plugins/PluginGallery.tsx, src/renderer/components/Settings/TransformerLabSettings.tsx
=> Add logic to filter experimental plugins

src/renderer/components/Experiment/Eval/EvalModal.tsx, src/renderer/components/Experiment/Generate/GenerateModal.tsx, src/renderer/components/Experiment/Train/TrainingModalLoRA.tsx
Fixes #452 
Depends on transformerlab/transformerlab-api#283
=> Fix rendering of eval and generate configs on update

src/renderer/components/Data/DataStore.tsx, src/renderer/components/Data/GeneratedDatasets.tsx, src/renderer/components/Data/LocalDatasets.tsx, src/renderer/components/Plugins/LocalPlugins.tsx, src/renderer/components/Plugins/PluginGallery.tsx
Replaced the generic error message based on the context of each one.
=> Changed the generic 'An error has occurred' message to more meaningful replacements.

src/renderer/components/Experiment/Interact/Interact.tsx
=> Remove chats from useEffect to reduce redundancy'

src/renderer/components/ModelZoo/ModelGroups.tsx, src/renderer/components/ModelZoo/ModelZoo.tsx, src/renderer/lib/api-client/allEndpoints.json, src/renderer/lib/api-client/endpoints.ts
The ModelGroups.tsx is now being rendered in the Model Groups tab in Model Zoo, which shows a sorted accordion list of model groups.
=> Added ModelGroups.tsx that is rendered inside Model Zoo in dev mode

src/renderer/components/Computer.tsx, src/renderer/components/Experiment/Eval/EvalModal.tsx, src/renderer/components/Experiment/Widgets/ModelProviderWidget.tsx, src/renderer/components/ModelZoo/ModelStore.tsx, src/renderer/components/Settings/AIProviderModal.tsx, src/renderer/components/Settings/TransformerLabSettings.tsx, src/renderer/lib/api-client/allEndpoints.json, src/renderer/lib/api-client/endpoints.ts, src/renderer/lib/api-client/hooks.ts, src/renderer/lib/transformerlab-api-sdk.ts
In thi PR, we replace all instances of Endpoints.Config with the new useAPI hook
=> Use useAPI for all references to the API /config endpoints

src/renderer/components/Experiment/Recipes/ListRecipes.tsx, src/renderer/components/Experiment/Recipes/RecipeCard.tsx, src/renderer/components/Experiment/Recipes/SelectedRecipe.tsx, src/renderer/components/Experiment/Recipes/index.tsx, src/renderer/components/Experiment/Recipes/recipeData.json, src/renderer/components/Experiment/SelectExperimentMenu.tsx, src/renderer/components/Plugins/PluginCard.tsx, src/renderer/components/Shared/ListArchitectures.tsx
This is a mockup of a modal that opens up when you select "create new experiment"
Right now it is hidden behind the "is the current experiment named 'dev'" flag so users should not see it.
=> Recipe Modal

src/renderer/components/Shared/DownloadProgressBox.tsx
The new Download Progress Bar now fully adapts to both light and dark themes,
Progress percentage is displayed inline inside the bar,
Bar filling is now smoothly animated, replacing the old static jumps,
An animated icon is shown next to the 'Downloading' label for real-time feedback
=> Changed the visuals in Download Progress Bar

src/renderer/components/ModelZoo/ModelGroups.tsx
Fixes for polling calls for jobs with ID of "{id}" and "-1".
=> Fix errant API calls on Model Zoo

src/renderer/components/Experiment/Interact/Batched/Batched.tsx, src/renderer/components/Experiment/Interact/ChatSettingsOnLeftHandSide.tsx, src/renderer/components/Experiment/Interact/Interact.tsx, src/renderer/components/Experiment/Interact/MainGenerationConfigKnobs.tsx, src/renderer/components/Experiment/Interact/TemplatedCompletion.tsx, src/renderer/components/Experiment/Interact/VisualizeGeneration.tsx, src/renderer/lib/api-client/chat.ts
- Fixes #537 
- Depends on transformerlab/transformerlab-api#354
=> Add Minimum P sampling for all generations

src/renderer/components/Experiment/Foundation/RunModelButton.tsx, src/renderer/lib/api-client/functions.ts
- Depends on transformerlab/transformerlab-api#358
=> Add model architecture on server start

src/renderer/components/Experiment/Workflows/WorkflowList/WorkflowList.tsx
Response to: https://github.com/transformerlab/transformerlab-app/issues/550
Discussed with Tony and decided a simple solution is displaying an alert message to the user letting them know the workflow has started and where to go to see progress.
=> Add Alert Message on Workflow Start

src/renderer/components/Experiment/Workflows/WorkflowList/NewWorkflowModal.tsx
Fixes #558 
Depends on transformerlab/transformerlab-api#378
=> Don't allow workflows of the same name

src/renderer/components/Experiment/Interact/Interact.tsx, src/renderer/components/MainAppPanel.tsx
=> Fix for issue #580

src/renderer/components/Computer.tsx
- This stops showing info about flash attention in Computer Tab as we have left it behind now
=> Suppress status about flash attention

src/renderer/components/Experiment/Foundation/ModelDetails.tsx
=> Fix ejecting models properly

src/renderer/components/Experiment/Recipes/ListRecipes.tsx, src/renderer/components/Experiment/Recipes/RecipeCard.tsx, src/renderer/components/Experiment/Recipes/SelectedRecipe.tsx
Filter recipes to display only those compatible with the user's hardware
=> Show recipes based on hardware compatibility

src/renderer/components/Experiment/Foundation/CurrentFoundationInfo.tsx, src/renderer/components/Experiment/Foundation/ModelDetails.tsx, src/renderer/components/Experiment/Foundation/SelectEmbeddingModel.tsx, src/renderer/components/MainAppPanel.tsx, src/renderer/lib/api-client/endpoints.ts
Fixes #607
Depends on transformerlab/transformerlab-api#422
=> Update multiple configs at once for select and eject models

src/renderer/components/Experiment/Foundation/ModelDetails.tsx
=> Fixes the delay of Ejecting the model

src/renderer/components/MainAppPanel.tsx
=> Reset chat history when pluginId change

src/renderer/components/Experiment/Foundation/ModelDetails.tsx, src/renderer/components/Experiment/SelectButton.tsx, src/renderer/components/MainAppPanel.tsx, src/renderer/components/ModelZoo/LocalModels.tsx
=> Avoid Race Conditions in Select and Eject buttons

src/renderer/components/Experiment/Workflows/WorkflowRuns/WorkflowRunDisplay.tsx
=> Add Progress Bar to Workflow Runs

src/renderer/components/Plugins/PluginGallery.tsx
UX improvement to better view the available plugins to install for your hardware
=> Hide incompatible plugins in dropdown

src/renderer/components/Plugins/PluginCard.tsx, src/renderer/components/Plugins/Plugins.tsx, src/renderer/lib/api-client/endpoints.ts
Depends on transformerlab/transformerlab-api#476
=> Make plugin install non experiment dependent

src/renderer/components/Data/AudioPlayer.tsx
=> Fix native element in audio player

src/renderer/components/Experiment/Interact/ChatPage.tsx, src/renderer/components/Experiment/Interact/Interact.tsx, src/renderer/components/Experiment/Interact/interactUtils.js, src/renderer/lib/api-client/chat.ts, src/renderer/lib/api-client/endpoints.ts, src/renderer/lib/transformerlab-api-sdk.ts
Ready for review, but marked as draft to NOT merge until both of these are merged (otherwise tool calling won't work):
https://github.com/transformerlab/transformerlab-api/pull/516
https://github.com/transformerlab/transformerlab-inference/pull/21
=> Fix Tool Calling

src/renderer/components/ModelZoo/ModelGroups.tsx
It now looks at:
- Group name
- Group Description
- Model Name
- Model Architecture
- Model Description
- Model Huggingface Repo
- Model Id
- Model Tags (if any)
=> Model groups search bar now looks at more things than just model groups name

src/renderer/components/Experiment/Audio/Audio.tsx
=> Add no model is running pop-up upon model disconnection to audio screen

src/renderer/components/Experiment/Audio/Audio.tsx, src/renderer/components/Experiment/Audio/BatchedAudioModal.tsx, src/renderer/lib/api-client/chat.ts, src/renderer/lib/transformerlab-api-sdk.ts
Depends on transformerlab/transformerlab-api#581
Fixes #791
=> Add batched generation button and modal for audio
